#!/bin/bash

source deploy.env

mkdir -p $IRTV_RUN_PATH

sudo docker rm -f $IRTV_CONTAINER_NAME
sudo docker build -t $IRTV_IMAGE_NAME .
sudo docker run -d -v "${IRTV_RUN_PATH}:/root/run" -e CONSUMER_KEY=$IRTV_CONSUMER_KEY -e CONSUMER_SECRET=$IRTV_CONSUMER_SECRET -e ACCESS_TOKEN=$IRTV_ACCESS_TOKEN -e ACCESS_TOKEN_SECRET=$IRTV_ACCESS_TOKEN_SECRET --name $IRTV_CONTAINER_NAME $IRTV_IMAGE_NAME
